### ISSUE TITLE
"modulePath" option is confusing (broken?)

### ISSUE THREAD

**Issue by kendallroth** [gethypervisual/gridsome-plugin-netlify-cms#1]
## What Happened

The `modulePath` configuration option currently only works when provided with a relative path (ie. prefixing the path with `./`), meaning that `./src/admin/index.js` works but `src/admin/index.js` does not.

## What I Expected

The `modulePath` configuration option should work with a path like `src/admin/index.js` but does not.

## Configuration

```
{
  use: "gridsome-plugin-netlify-cms",
  options: {
    // Source path to Netlify CMS configuration
    configPath: "static/admin/config.yml",
    htmlTitle: "CMS - Family Merchant",
    // Source path to Netlify module
    //  NOTE: This should work without the "./" prefix
    modulePath: "./src/admin/index.js",
    // Site path to Netlify CMS
    publicPath: "/admin",
  },
},
```

**Comment by tobymarsden** [comment]
@kendallroth thanks! published as v1.0.4

**Comment by kendallroth** [comment]
@tobymarsden Blown away by the level of responsiveness, can confirm issue is resolved!

**Comment by tobymarsden** [comment]
@kendallroth was just working on a new feature, so had the file open already 😄
