### ISSUE TITLE
Where I am supposed to put the netlify-cms module?

### ISSUE THREAD

**Issue by ahsath** [gethypervisual/gridsome-plugin-netlify-cms#4]
I'm following [the guide](https://www.netlifycms.org/docs/add-to-your-site/#installing-with-npm) on netlify cms but I don't know where I am supposed to put the netlify-cms module in order to work other than using the cdn directly in a `index.hmtl` file on `src/admin/index.html`, or it does work automatically?

**Comment by tobymarsden** [comment]
Hi @ahsath!

If you follow the [readme from the gridsome-plugin-netlify-cms repo](https://github.com/gethypervisual/gridsome-plugin-netlify-cms/blob/master/README.md) it should all work automatically. This plugin will call the `netlify-cms` module for you so you don't need to do this manually.

You can override things and import the module yourself if you need using the [`modulePath`](https://github.com/gethypervisual/gridsome-plugin-netlify-cms/blob/master/README.md#modulepath) option, but I wouldn't do this until you've got it basically working first.

Don't forget to include [Netlify's `config.yml` file](https://www.netlifycms.org/docs/add-to-your-site/#configuration) at `src/admin/config.yml`, or to [add the plugin to your `gridsome.config.js` file](https://github.com/gethypervisual/gridsome-plugin-netlify-cms/blob/master/README.md#how-to-use).

**Comment by ahsath** [comment]
Thank you
